### ISSUE TITLE
contents of input box too far down on IE

### ISSUE THREAD

**Issue by garyfoster** [radicalbear/bootstrap_datetimepicker#1]
This is what it looks like on IE 10. Looks fine in Safari, Chrome and FF.

![screen shot 2014-09-01 at 2 08 40 pm](https://cloud.githubusercontent.com/assets/1126133/4111282/7d7ae1c4-3203-11e4-86b8-a9d9a1d7dcaa.png)

**Comment by plicjo** [comment]
@garyfoster, I upgraded this to the latest version of the vendored package. Has this been resolved?

**Comment by plicjo** [comment]
It should be working fine in IE now.
