### ISSUE TITLE
option to not default to today/now

### ISSUE THREAD

**Issue by garyfoster** [radicalbear/bootstrap_datetimepicker#5]
Currently when the input receives focus, the current date/time is inserted automatically. This may be a good feature but in some cases we would not want this to occur.

**Comment by plicjo** [comment]
You can put a data attribute on the date-picker to remove the automatic current date selection.

https://github.com/radicalbear/bootstrap_datetimepicker/blob/master/app/assets/javascripts/bootstrap_datetimepicker/dates.coffee#L59

Add a `data-default-current-date => false` to the input and you should get the behavior that you're looking for.
